version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "kevinmorio"
    assignees:
      - "kevinmorio"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "kevinmorio"
    assignees:
      - "kevinmorio"
    commit-message:
      prefix: "chore"
      include: "scope"