# Copyright (C) 2025 CISPA Helmholtz Center for Information Security
# Author: Kevin Morio <kevin.morio@cispa.de>
#
# This file is part of go-annotate.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the MIT License as published by
# the Open Source Initiative.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# MIT License for more details.
#
# You should have received a copy of the MIT License
# along with this program. If not, see <https://opensource.org/licenses/MIT>.

run:
  timeout: 10m
linters:
  enable-all: false
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - gocritic
    - gofumpt
    - goimports
    - gomodguard
    - revive
    - gosimple
    - govet
    - gosec
    - godot
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - testifylint
    - typecheck
    - unconvert
    - unparam
    - unused
linters-settings:
  gocyclo:
    min-complexity: 75
  lll:
    line-length: 200
  ireturn:
    allow:
      - error
      - generic
      - Term
  mnd:
    ignored-numbers:
      - '0'
      - '1'
      - '2'
  gocritic:
    disabled-checks:
      - captLocal 
      - unslice
      - ifElseChain

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - gosec
        - revive
    - path: log\.go
      linters:
        - revive
      text: "stutters"
    - path: log\.go
      linters:
        - staticcheck
      text: "SA6002"
    - linters:
        - staticcheck
      text: "SA6002"